name = "qms-api"
main = "src/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "qms-api-production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "qms-production"
database_id = "" # Will be filled when creating the database

[env.testing]
name = "qms-api-testing"

[[env.testing.d1_databases]]
binding = "DB"
database_name = "qms-testing"
database_id = "" # Will be filled when creating the database

# Local development configuration
[[d1_databases]]
binding = "DB"
database_name = "qms-local"
database_id = ""

[vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"

[env.testing.vars]
ENVIRONMENT = "testing"